const itemLabels = {
  hikeBag: "Comfortable hiking backpack",
  hikeBoots: "Comfortable hiking boots or trail shoes with good traction",
  shortsHike: "Shorts can be worn on this hike",
  pants: "Long hiking pants",
  top: "Light top",
  thermals: "Thermal mid-layers",
  layers: "Lightweight, breathable outer layers (weather-appropriate)",
  water: "At least 2 litres of water",
  extraWater: "At least 3 litres of water",
  hikePoles: "Hiking poles",
  snacks: "High energy snacks",
  salts: "Hydration salts / Electrolytes",
  sunscreen: "Sunscreen",
  hat: "Hat",
  mittens: "Water-resistant gloves/mittens",
  buff: "Buff",
  gaiters: "Gaiters",
  clothesChange: "Post-hike change of clothes",
  socksShoes: "Change of socks and shoes",
  camera: "Camera (optional)",
  rainJacket: "Rain jacket / Poncho",
  firstAid: "First aid kit",
  powerBank: "Power bank",
  identification: "Identification",
  medIns: "Medical cover card",
  trashBag: "Trash-bag",
  personalStuff: "Personal Items",
  attitude: "A great attitude and a helping hand - we look out for each other",
  spirit: "Your fighting spirit and great sense of humour",
  petho: "Petho is requested to be left at home because once you're out in the elements there's no shame in the nature game"
};

export default itemLabels;
